log stdout debug
bind-address ::
api :: 8080
!
route add e164 0119273 sip tel.arf20.com
!
acl test-acl permit 0119999
acl test-acl deny 4321
!
route-map example-rm permit 10
 match e164 test-acl
 set local-preference 50
exit
!
trip 10
 ls-id 0.0.0.10
 timers 60 30 120 10 180 30 30
 default local-pref 100
 default metric 100
 peer 192.168.122.152 remote-itad 20
 peer 192.168.122.152 route-map example-rm in
exit

