log stdout debug
bind-address ::
!
route add e164 0119273 sip tel.arf20.com
!
acl test-acl permit 1234
acl test-acl deny 4321
!
route-map example-rm
 match e164 test-acl
 set local-preference 50
exit
!
trip 10
 ls-id 0.0.0.10
 timers 240
 peer 10.0.0.1 remote-itad 20
exit

